%.pdf: %.svg
	inkscape -f $< -A $@ --export-text-to-path --export-area-page

drawings: \
canonical-left-car.pdf \
canonical-right-car.pdf \
contractSOSLeft-car.pdf \
contractSOSLeft-nut.pdf \
contractSOSRight-car.pdf \
contractSOSRight-nut.pdf \
contract_sos_left-nut.pdf \
contract_sos_right-nut.pdf \
E-O-matrix-car.pdf \
E-Os-matrix-car.pdf \
expectation-car.pdf \
expectation-nut.pdf \
expectation_boundary_tensors-car.pdf \
expectation_boundary_tensors-nut.pdf \
iteration-nut.pdf \
matmul-car.pdf \
operator_site_tensor-car.pdf \
operator_site_tensor-nut.pdf \
state_site_tensor-car.pdf \
state_site_tensor-nut.pdf \
